import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { join } from 'node:path'
const runtimeErrors = new WeakMap<Page, string[]>()
test.beforeEach(({ page }) => { const errors: string[] = []; runtimeErrors.set(page, errors); page.on('pageerror', (error) => errors.push(error.message)) })
test.afterEach(({ page }) => { expect(runtimeErrors.get(page)).toEqual([]) })

// These tests use the running P17 service and its actual persisted archive.
// No request interception, synthetic success responses or new model execution.
test('real stock search, candlestick, stored SMA200 and missing session evidence', async ({ page }) => {
  await page.goto('/market'); await page.getByRole('textbox', { name: 'Search securities' }).fill('RELIANCE')
  await expect(page.locator('a.security-link[href="/stocks/tejhq%3Aisin%3AINE002A01018"]')).toBeVisible()
  await page.locator('a.security-link[href="/stocks/tejhq%3Aisin%3AINE002A01018"]').click()
  await expect(page.getByRole('heading', { name: 'Stock analysis', exact: true })).toBeVisible()
  await expect(page.getByTestId('financial-chart')).toBeVisible()
  await expect(page.getByText(/sma_200: \d+ evidenced values/)).toBeVisible()
  await expect(page.getByText('₹', { exact: true })).toHaveCount(0)
  await page.getByLabel('From', { exact: true }).fill('2023-11-10'); await page.getByLabel('To', { exact: true }).fill('2023-11-14'); await page.getByRole('button', { name: 'Apply dates' }).click()
  await expect(page.getByText('3 session slots · 1 missing prices')).toBeVisible()
  await expect(page.getByRole('cell', { name: '2023-11-12', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Unavailable', exact: true })).toHaveCount(5)
  await page.getByRole('button', { name: '1Y', exact: true }).click()
  await expect(page.getByText(/sma_200: \d+ evidenced values/)).toBeVisible()
  await page.getByRole('button', { name: 'RSI 14', exact: true }).click()
  await expect(page.getByText(/rsi_14: \d+ evidenced values/)).toBeVisible()
  await page.screenshot({ path: join(process.env.ALPHALENS_BROWSER_OUTPUT_DIR ?? 'test-results', 'real-stock-desktop.png'), fullPage: true })
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(accessibility.violations).toEqual([])
  await page.getByRole('combobox', { name: 'Select a security for analysis' }).fill('INE467B01029')
  await page.getByRole('option').filter({ hasText: 'INE467B01029' }).getByRole('button').click()
  await expect(page).toHaveURL(/stocks\/tejhq%3Aisin%3AINE467B01029$/)
  await expect(page.getByRole('heading', { name: 'TCS', exact: true })).toBeVisible()
  await expect(page.getByText(/sma_200: \d+ evidenced values/)).toBeVisible()
})
test('actual model metrics, holdout labels and unresolved economic backtest', async ({ page }) => {
  await page.goto('/research'); await expect(page.getByRole('heading', { name: 'ML research lab', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Hist gradient boosting', exact: true }).first()).toBeVisible()
  await page.getByLabel('Evaluation period').selectOption('2026')
  await expect(page.getByText('2026 final holdout — already evaluated under the frozen protocol.')).toBeVisible()
  await expect(page.getByRole('cell', { name: /Hist gradient boosting/ }).first()).toBeVisible()
  await page.screenshot({ path: join(process.env.ALPHALENS_BROWSER_OUTPUT_DIR ?? 'test-results', 'real-research-desktop.png'), fullPage: true })
  await page.getByLabel('Evaluation period').selectOption('development'); await page.getByLabel('Model task').selectOption('regression'); await page.getByLabel('Model family').selectOption('ridge')
  await expect(page.getByRole('cell', { name: 'Ridge', exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'RMSE', exact: true })).toBeVisible()
  await page.goto('/backtests'); await expect(page.getByText('258', { exact: true })).toBeVisible(); await expect(page.getByText('198', { exact: true })).toBeVisible(); await expect(page.getByText('18', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Inspect backtest/ }).first().click()
  await expect(page.getByRole('heading', { name: 'Full-path economic metrics' })).toBeVisible()
  await expect(page.getByText('Unavailable', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Stored closed-trade diagnostics')).toBeVisible()
  await page.screenshot({ path: join(process.env.ALPHALENS_BROWSER_OUTPUT_DIR ?? 'test-results', 'real-backtest-desktop.png'), fullPage: true })
})
test('navigation, true unavailable services, local settings and responsive keyboard controls', async ({ page }) => {
  await page.goto('/'); await expect(page.getByRole('heading', { name: 'Research overview', exact: true })).toBeVisible()
  await expect(page.getByTestId('financial-chart')).toBeVisible()
  await page.screenshot({ path: join(process.env.ALPHALENS_BROWSER_OUTPUT_DIR ?? 'test-results', 'real-overview-desktop.png'), fullPage: true })
  await page.goto('/opportunities'); await expect(page.getByRole('heading', { name: 'Current-session opportunities are unavailable' })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Evidence unavailable' }).first()).toBeVisible()
  for (const route of ['/portfolios', '/paper']) {
    await page.goto(route); await expect(page.getByText('Portfolio database is not configured.')).toBeVisible(); await expect(page.getByRole('button', { name: /place order|buy|sell/i })).toHaveCount(0)
  }
  await page.goto('/data-health'); await expect(page.getByText('2026-10-06', { exact: true }).first()).toBeVisible(); await expect(page.getByText(/44 HIGH OS security findings/)).toBeVisible()
  await page.context().setOffline(true); await page.getByRole('button', { name: 'Refresh diagnostic reads' }).click()
  await expect(page.getByText('The local backend is disconnected. Start P17 and retry.').first()).toBeVisible()
  await page.context().setOffline(false); await page.getByRole('button', { name: 'Refresh diagnostic reads' }).click()
  await expect(page.getByText('ALIVE', { exact: true })).toBeVisible()
  await page.goto('/settings'); await page.getByRole('button', { name: 'Light', exact: true }).click(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light'); await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/market'); await page.getByRole('button', { name: 'Open navigation' }).click(); await page.getByRole('link', { name: 'ML Research Lab', exact: true }).click(); await expect(page.getByRole('heading', { name: 'ML research lab', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Hist gradient boosting', exact: true }).first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: join(process.env.ALPHALENS_BROWSER_OUTPUT_DIR ?? 'test-results', 'real-research-mobile.png'), fullPage: true })
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze(); expect(accessibility.violations).toEqual([])
})

test('bounded persisted prediction inspection retains OOS role and model-estimate language', async ({ page }) => {
  await page.goto('/research?horizon=5'); await page.getByLabel('Evaluation period').selectOption('2026')
  await page.getByRole('button', { name: 'Inspect hist_gradient_boosting 2026', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible(); await expect(dialog.getByText(/MODEL ESTIMATE · NOT GUARANTEED/)).toBeVisible()
  await dialog.getByRole('combobox', { name: 'Choose prediction security' }).fill('RELIANCE')
  await dialog.getByRole('option').filter({ hasText: 'INE002A01018' }).getByRole('button').click()
  await dialog.getByRole('button', { name: 'Read predictions', exact: true }).click()
  await expect(dialog.getByRole('cell', { name: 'FOLD_TEST', exact: true }).first()).toBeVisible()
  await dialog.locator('.evidence-note').last().locator('summary').first().click()
  await expect(dialog.getByText('CHECKSUM_VERIFIED_P9_FOLD_TEST', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0)
})
