import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { z } from 'zod'
import { Info, LockKeyhole } from 'lucide-react'
import { get } from '../api/client'
import type { JsonObject } from '../api/contracts'
import { holdingsSchema, ordersSchema, paperMetadataSchema, paperPerformanceSchema, portfolioPerformanceSchema, portfolioSchema, tradesSchema, transactionsSchema } from '../api/accounts'
import { exact, readable } from '../lib/format'
import { Badge, Empty, EvidenceNote, Heading, Panel, QueryState, Stat } from '../components/ui'

function fields(value: unknown): JsonObject { return value && typeof value === 'object' && !Array.isArray(value) ? value as JsonObject : {} }
function records(value: unknown): JsonObject[] { return Array.isArray(value) ? value.filter((r) => r && typeof r === 'object' && !Array.isArray(r)) as JsonObject[] : [] }
export function Portfolios() { return <AccountWorkspace paper={false} /> }
export function Paper() { return <AccountWorkspace paper /> }
function AccountWorkspace({ paper }: { paper: boolean }) {
  const prefix = paper ? '/paper/accounts' : '/portfolios'; const [selected, setSelected] = useState('')
  const list = useQuery({ queryKey: [paper ? 'paper-accounts' : 'portfolios'], queryFn: ({ signal }) => get(`${prefix}?limit=100`, z.array(portfolioSchema), signal) })
  const id = selected || (list.data?.data[0]?.portfolio_id as string | undefined)
  return <><Heading eyebrow={paper ? 'P16 · Simulated account evidence' : 'P15 · Recorded holdings & FIFO accounting'} title={paper ? 'Paper trading' : 'Portfolio analytics'}>{paper ? 'Read-only simulated orders, fills and account history.' : 'Inspect manually recorded holdings and auditable ledger state.'}<br />{paper ? 'No order placement or broker execution.' : 'Unavailable valuations are never replaced with zero.'}</Heading>
    <div className={`notice ${paper ? 'accent' : ''}`}><LockKeyhole size={20} /><p><strong>{paper ? 'Simulation only · read-only workspace' : 'Read-only portfolio workspace'}</strong> {paper ? 'P17 exposes no execution/write routes. Existing next-evidenced-open and idempotency rules remain unchanged.' : 'Recorded executions are not exchange-verified. This archive cannot silently value real user holdings.'}</p><Badge tone={paper ? 'accent' : 'neutral'}>{paper ? 'SIMULATED' : 'USER RECORDED'}</Badge></div>
    <Panel title={paper ? 'Paper accounts' : 'Recorded portfolios'} subtitle="Persisted PostgreSQL records only"><QueryState query={list}>{list.data && (list.data.data.length ? <label className="account-select">{paper ? 'Select simulated account' : 'Select portfolio'}<select value={id} onChange={(e) => setSelected(e.target.value)} aria-label={paper ? 'Paper account' : 'Portfolio'}>{list.data.data.map((account) => <option key={String(account.portfolio_id)} value={String(account.portfolio_id)}>{String(account.portfolio_name ?? account.portfolio_id)} · {String(account.portfolio_type ?? 'PAPER')}</option>)}</select></label> : <Empty title={paper ? 'No paper accounts recorded' : 'No portfolio records'}>The connected database contains no records. This read-only dashboard does not create accounts or trades.</Empty>)}
      <EvidenceNote evidence={list.data} /></QueryState>{list.data?.page?.has_more && <p className="warning-text">The first 100 accounts are shown; additional account browsing requires a narrower future server filter.</p>}</Panel>
    {list.isError && <Panel title="Local database configuration"><p className="caption">Configure the existing P17 database connection privately in its process environment and use the migrated P15/P16 schema. No credentials belong in this frontend or browser storage.</p><p className="caption">Historical stocks and ML research can remain available independently of the portfolio database.</p></Panel>}
    {id && list.isSuccess && <AccountDetail key={`${paper}-${id}`} prefix={prefix} id={id} paper={paper} />}
  </>
}
function AccountDetail({ prefix, id, paper }: { prefix: string; id: string; paper: boolean }) {
  const [tab, setTab] = useState(paper ? 'orders' : 'holdings'); const [offset, setOffset] = useState(0)
  const path = `${prefix}/${encodeURIComponent(id)}`
  const metadata = useQuery({ queryKey: ['account', path], queryFn: ({ signal }) => get(path, paper ? paperMetadataSchema : portfolioSchema, signal) })
  const performance = useQuery({ queryKey: ['account-performance', path], queryFn: ({ signal }) => get(`${path}/performance?limit=100`, paper ? paperPerformanceSchema : portfolioPerformanceSchema, signal) })
  const rows = useQuery({ queryKey: ['account-view', path, tab, offset], queryFn: ({ signal }) => get(`${paper && tab === 'holdings' ? '/portfolios/' + encodeURIComponent(id) : path}/${tab}?limit=100&offset=${offset}`, tab === 'holdings' ? holdingsSchema : tab === 'transactions' ? transactionsSchema : tab === 'orders' ? ordersSchema : tradesSchema, signal) })
  const account = paper ? fields(metadata.data?.data.portfolio) : metadata.data?.data ?? {}
  const state = paper ? fields(performance.data?.data.performance) : fields(performance.data?.data.accounting)
  const all = records(rows.data?.data[tab === 'holdings' ? 'positions' : tab])
  const columns = tab === 'holdings' ? ['transaction_symbol', 'security_id', 'quantity', 'cost_basis', 'realized_pnl', 'fees'] : paper ? tab === 'orders' ? ['order_id', 'security_id', 'side', 'quantity', 'decision_session', 'intent_source'] : ['fill_id', 'order_id', 'session', 'quantity', 'observed_open', 'simulated_price', 'fees']
    : tab === 'holdings' ? ['transaction_symbol', 'security_id', 'quantity', 'cost_basis', 'realized_pnl', 'fees'] : ['transaction_id', 'kind', 'symbol', 'session', 'quantity', 'price', 'fees', 'classification']
  return <><Panel title={String(account.portfolio_name ?? 'Account metadata')} subtitle={`Stable record: ${id}`}><QueryState query={metadata}><dl className="detail-grid"><dt>Portfolio type</dt><dd>{String(account.portfolio_type ?? 'Unavailable')}</dd><dt>Currency</dt><dd>{String(account.base_currency ?? 'Unavailable')}</dd><dt>Classification</dt><dd>{String(account.classification ?? 'Unavailable')}</dd><dt>Created</dt><dd>{String(account.created_at ?? 'Unavailable')}</dd><dt>Accounting policy</dt><dd>{String(fields(account.accounting_policy).version ?? 'Unavailable')}</dd></dl><EvidenceNote evidence={metadata.data} /></QueryState></Panel>
    <Panel title={paper ? 'Simulated performance evidence' : 'Portfolio accounting & valuation'} subtitle="Exact persisted values; unavailable full valuations remain unavailable"><QueryState query={performance}><div className="stats-grid"><Stat label="Cash" value={exact(state.cash)} /><Stat label="Realized P&L" value={exact(state.realized_pnl)} note={paper ? 'Simulated only' : 'Per-position ledger values below'} /><Stat label="Market / portfolio value" value={exact(paper ? state.equity : performance.data?.data.portfolio_value)} /><Stat label="Unrealized P&L" value={exact(paper ? state.unrealized_pnl : performance.data?.data.unrealized_pnl)} /></div>
      <div className="notice warning"><Info size={18} /><p>Only P15/P16 returned accounting and valuation evidence is displayed. An absent equity curve, current risk or current signal is unavailable; no allocation chart is constructed from unknown prices.</p></div><EvidenceNote evidence={performance.data} /></QueryState></Panel>
    {paper && performance.data && <Panel title="Simulation accounting details"><div className="metric-grid">{['starting_capital', 'available_cash', 'reserved_cash', 'total_pnl', 'session_pnl', 'fees', 'simulated_fill_count'].map((key) => <Stat key={key} label={readable(key)} value={exact(state[key])} />)}</div><p className="caption">{String(state.disclaimer ?? 'SIMULATED · NOT REAL EXECUTION')}</p></Panel>}
    <Panel title={paper ? 'Simulated positions & execution records' : 'Ledger records'} actions={<div className="segmented">{(paper ? ['holdings', 'orders', 'trades'] : ['holdings', 'transactions']).map((value) => <button key={value} aria-pressed={tab === value} onClick={() => { setTab(value); setOffset(0) }}>{readable(value)}</button>)}</div>}>
      <QueryState query={rows}>{all.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Scrollable evidence table"><table><thead><tr>{columns.map((key) => <th key={key}>{readable(key)}</th>)}{paper && tab === 'orders' && <th>State</th>}</tr></thead><tbody>{all.map((row, i) => <tr key={String(row.transaction_id ?? row.order_id ?? row.fill_id ?? row.security_id ?? i)}>{columns.map((key) => <td className={['quantity', 'price', 'fees', 'cost_basis', 'realized_pnl'].includes(key) ? 'numeric' : 'breakable'} key={key}>{typeof row[key] === 'string' ? String(row[key]) : exact(row[key])}</td>)}{paper && tab === 'orders' && <td>{String(fields(rows.data?.data.order_states)[String(row.order_id)] ?? 'Unavailable')}</td>}</tr>)}</tbody></table></div> : <Empty title={`No ${tab} in this page`}>No records have been invented.</Empty>}
        <div className="pager"><span>Page {offset / 100 + 1} · recorded evidence</span><div><button className="button small" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 100))}>Previous</button><button className="button small" disabled={!rows.data?.page?.has_more || offset >= 10000} onClick={() => setOffset(offset + 100)}>Next</button></div></div><EvidenceNote evidence={rows.data} /></QueryState></Panel>
    {paper && performance.data && <Panel title="Persisted simulation history" subtitle="Read-only chart-ready records from P16; no reconstructed valuations"><div className="table-scroll" tabIndex={0} role="region" aria-label="Scrollable evidence table"><table><thead><tr><th>Session</th><th>Equity</th><th>P&L</th><th>Freshness / evidence</th></tr></thead><tbody>{records(performance.data.data.equity).map((row, i) => <tr key={String(row.session ?? i)}><td>{String(row.session ?? 'Unavailable')}</td><td className="numeric">{exact(row.portfolio_value ?? row.equity)}</td><td className="numeric">{exact(row.total_pnl)}</td><td>{String(row.freshness ?? row.quality ?? 'Unavailable')}</td></tr>)}</tbody></table></div>{!records(performance.data.data.equity).length && <Empty title="No persisted simulated equity history" />}</Panel>}
  </>
}
