import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowUpRight, Info } from 'lucide-react'
import { collect, get } from '../api/client'
import { backtestSchema, backtestDetailSchema, backtestPerformanceSchema, type Backtest } from '../api/contracts'
import { exact, graphicNumber, metric, partitionBacktests, readable } from '../lib/format'
import { Badge, Drawer, Empty, EvidenceNote, Heading, Panel, QueryState, Stat } from '../components/ui'
import { Chart } from '../components/Chart'

export function Backtests() {
  const runs = useQuery({ queryKey: ['backtests'], queryFn: ({ signal }) => collect('/research/backtests', backtestSchema, {}, signal, 1000) })
  const [filters, setFilters] = useState<Record<string, string>>({}); const [page, setPage] = useState(0); const [selected, setSelected] = useState<Backtest | null>(null)
  const rows = runs.data?.data.filter((row) => Object.entries(filters).every(([key, value]) => !value || String(row[key]) === value)) ?? []
  const counts = partitionBacktests(runs.data?.data ?? [])
  const choices = [['model_family', 'Model'], ['horizon', 'Horizon'], ['phase', 'Research phase'], ['selection_rule', 'Strategy'], ['cost_scenario', 'Cost assumption'], ['status', 'Evidence status']]
  return <><Heading eyebrow="P10 · Stored hypothetical outcomes" title="Backtesting evidence">Review actual persisted research scenarios.<br />Closed trades and full-path economics are distinct.</Heading>
    <div className="notice warning"><Info size={18} /><p>Missing prices, identity gaps and unreconciled corporate actions prevent complete economic outcomes. Unavailable returns stay unavailable; no terminal values or adjustments are invented.</p></div>
    <div className="stats-grid"><Stat label="Stored runs" value={runs.isSuccess ? runs.data.data.length : 'Unavailable'} note="Existing backtests; no recomputation" /><Stat label="Corporate-action uncertainty only" value={runs.isSuccess ? counts.actions : 'Unavailable'} note="Full-path economics unresolved" /><Stat label="Actions + price / identity gaps" value={runs.isSuccess ? counts.both : 'Unavailable'} note="Multiple missing economic inputs" /><Stat label="Price / identity gaps only" value={runs.isSuccess ? counts.gaps : 'Unavailable'} note="No reliable terminal or session value" /></div>
    <Panel title="Research scenario directory" subtitle="Every metric is read from the original stored run"><div className="filters dense">{choices.map(([key, title]) => <label key={key}>{title}<select aria-label={`Backtest ${title.toLowerCase()}`} value={filters[key] ?? ''} onChange={(e) => { setFilters({ ...filters, [key]: e.target.value }); setPage(0) }}><option value="">All</option>{[...new Set(runs.data?.data.map((row) => String(row[key])))].sort().map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label>)}</div>
      <QueryState query={runs}><div className="table-scroll" tabIndex={0} role="region" aria-label="Scrollable evidence table"><table><thead><tr><th>Model / horizon</th><th>Period / task</th><th>Strategy</th><th>Cost assumption</th><th>Economic evidence</th><th>Unresolved trades</th><th>Details</th></tr></thead><tbody>{rows.slice(page * 25, (page + 1) * 25).map((row) => <tr key={row.backtest_id}><td><strong>{readable(row.model_family)}</strong><span className="cell-secondary">{row.horizon} sessions</span></td><td>{row.phase === 'development' ? 'Development OOS' : row.phase === '2026' ? '2026 final holdout' : '2025 confirmation'}<span className="cell-secondary">{row.task}</span></td><td>{readable(row.selection_rule)}</td><td>{readable(row.cost_scenario)}<span className="cell-secondary">Development assumption</span></td><td><Badge tone={row.status === 'UNRESOLVED_ECONOMIC_OUTCOMES' ? 'warning' : 'neutral'}>{readable(row.status)}</Badge></td><td className="numeric">{row.unresolved_trade_count}</td><td><button className="icon-button" aria-label={`Inspect backtest ${row.backtest_id}`} onClick={() => setSelected(row)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table></div>
        {!rows.length && <Empty title="No stored scenario matches" />}<div className="pager"><span>{rows.length} matching scenarios</span><div><button className="button small" disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1}</span><button className="button small" disabled={(page + 1) * 25 >= rows.length} onClick={() => setPage(page + 1)}>Next</button></div></div><EvidenceNote evidence={runs.data} /></QueryState></Panel>
    {selected && <Drawer title={`${readable(selected.model_family)} · ${selected.horizon}D backtest`} close={() => setSelected(null)}><BacktestDetails run={selected} /></Drawer>}
  </>
}
function BacktestDetails({ run }: { run: Backtest }) {
  const detail = useQuery({ queryKey: ['backtest', run.backtest_id], queryFn: ({ signal }) => get(`/research/backtests/${run.backtest_id}`, backtestDetailSchema, signal) })
  const [offset, setOffset] = useState(0)
  const performance = useQuery({ queryKey: ['backtest-performance', run.backtest_id, offset], queryFn: ({ signal }) => get(`/research/backtests/${run.backtest_id}/performance?limit=500&offset=${offset}`, backtestPerformanceSchema, signal) })
  const unresolved = run.status === 'UNRESOLVED_ECONOMIC_OUTCOMES'
  const option = useMemo(() => ({ grid: { left: 65, right: 20, top: 20, bottom: 50 }, tooltip: { trigger: 'axis', renderMode: 'richText' },
    xAxis: { type: 'category', data: performance.data?.data.equity.map((p) => p.session) ?? [], axisLabel: { color: '#94a3b8' } },
    yAxis: { type: 'value', scale: true, axisLabel: { color: '#94a3b8' }, splitLine: { lineStyle: { color: '#243047' } } },
    series: [{ name: 'Stored equity · INR', type: 'line', showSymbol: false, connectNulls: false, lineStyle: { color: '#50cbd5', width: 2 }, data: performance.data?.data.equity.map((p) => graphicNumber(p.portfolio_value)) ?? [] }] }), [performance.data])
  return <QueryState query={detail}>{detail.data && <><Badge tone={unresolved ? 'warning' : 'neutral'}>{readable(run.status)}</Badge><p className="caption">{run.phase === '2026' ? 'Stored final-holdout scenario. No reevaluation.' : 'Stored OOS research scenario.'} · Costs are assumptions, not verified broker charges.</p>
    <h3>Full-path economic metrics</h3><div className="metric-grid">{['total_return', 'cagr', 'sharpe', 'sortino', 'maximum_drawdown', 'turnover'].map((key) => <Stat key={key} label={readable(key)} value={unresolved ? 'Unavailable' : metric(detail.data!.data.summary[key], ['total_return', 'cagr', 'maximum_drawdown'].includes(key))} />)}</div>
    {unresolved && <div className="notice warning"><Info size={18} /><p>Complete equity, return and drawdown interpretation is blocked. Closed-trade diagnostics below describe only resolved trades and are not full-strategy returns.</p></div>}
    <h3>Stored closed-trade diagnostics</h3><div className="metric-grid">{['closed_trade_count', 'unresolved_trade_count', 'win_rate', 'profit_factor', 'average_trade_return', 'average_holding_sessions'].map((key) => <Stat key={key} label={readable(key)} value={key.endsWith('count') ? exact(detail.data!.data.summary[key]) : metric(detail.data!.data.summary[key], ['win_rate', 'average_trade_return'].includes(key))} />)}</div>
    <h3>Economic evidence gaps</h3>{Object.entries(run.cause_counts).length ? <ul className="evidence-list">{Object.entries(run.cause_counts).map(([key, value]) => <li key={key}><span>{readable(key)}</span><Badge tone="warning">{value} stored events</Badge></li>)}</ul> : <p className="caption">No unresolved economic cause was recorded for this run. Raw-price and research assumptions still apply.</p>}
    <h3>Stored equity evidence</h3><QueryState query={performance}>{performance.data && <>{performance.data.data.equity.some((point) => point.portfolio_value !== null) ? <><Chart option={option} label="Stored backtest equity page; missing values break the curve" height={300} /><p className="caption">Only this bounded page is shown. Unknown valuation slots remain gaps; {unresolved ? 'this partial path is not a complete strategy equity curve.' : 'raw-unadjusted research outcomes are not production-validated.'}</p><div className="pager"><span>{performance.data.data.equity.length} returned session slots</span><div><button className="button small" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 500))}>Previous</button><button className="button small" disabled={!performance.data.page?.has_more || offset >= 10000} onClick={() => setOffset(offset + 500)}>Next</button></div></div></> : <Empty title="No evidenced equity values in this page">The unavailable economic path has not been filled or interpolated.</Empty>}<p className="caption">Benchmark comparison: {performance.data.data.benchmark_status}</p><EvidenceNote evidence={performance.data} /></>}</QueryState>
    <details className="technical-details"><summary>Frozen scenario & audit lineage</summary><pre>{JSON.stringify({ identity: detail.data.data.summary.identity, economic_evidence: run }, null, 2)}</pre></details><EvidenceNote evidence={detail.data} />
  </>}</QueryState>
}
